const UPGRADE_STATES = Object.freeze({
  FRESH_INSTALL: 'FRESH_INSTALL',
  EXISTING_INSTALL_READY: 'EXISTING_INSTALL_READY',
  PRE_UPGRADE_BACKUP_REQUIRED: 'PRE_UPGRADE_BACKUP_REQUIRED',
  PRE_UPGRADE_BACKUP_IN_PROGRESS: 'PRE_UPGRADE_BACKUP_IN_PROGRESS',
  PRE_UPGRADE_BACKUP_VERIFIED: 'PRE_UPGRADE_BACKUP_VERIFIED',
  MIGRATION_REQUIRED: 'MIGRATION_REQUIRED',
  MIGRATION_IN_PROGRESS: 'MIGRATION_IN_PROGRESS',
  MIGRATION_COMPLETED: 'MIGRATION_COMPLETED',
  UPGRADE_VALIDATION_REQUIRED: 'UPGRADE_VALIDATION_REQUIRED',
  UPGRADE_COMPLETED: 'UPGRADE_COMPLETED',
  RECOVERY_REQUIRED: 'RECOVERY_REQUIRED',
  FAILED_CLOSED: 'FAILED_CLOSED',
});

const TERMINAL_STATES = new Set([
  UPGRADE_STATES.FRESH_INSTALL,
  UPGRADE_STATES.EXISTING_INSTALL_READY,
  UPGRADE_STATES.UPGRADE_COMPLETED,
  UPGRADE_STATES.RECOVERY_REQUIRED,
  UPGRADE_STATES.FAILED_CLOSED,
]);

const ALLOWED_TRANSITIONS = Object.freeze({
  [UPGRADE_STATES.FRESH_INSTALL]: [],
  [UPGRADE_STATES.EXISTING_INSTALL_READY]: [],
  [UPGRADE_STATES.PRE_UPGRADE_BACKUP_REQUIRED]: [
    UPGRADE_STATES.PRE_UPGRADE_BACKUP_IN_PROGRESS,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.PRE_UPGRADE_BACKUP_IN_PROGRESS]: [
    UPGRADE_STATES.PRE_UPGRADE_BACKUP_VERIFIED,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.PRE_UPGRADE_BACKUP_VERIFIED]: [
    UPGRADE_STATES.MIGRATION_REQUIRED,
    UPGRADE_STATES.MIGRATION_IN_PROGRESS,
    UPGRADE_STATES.UPGRADE_VALIDATION_REQUIRED,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.MIGRATION_REQUIRED]: [
    UPGRADE_STATES.MIGRATION_IN_PROGRESS,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.MIGRATION_IN_PROGRESS]: [
    UPGRADE_STATES.MIGRATION_COMPLETED,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.MIGRATION_COMPLETED]: [
    UPGRADE_STATES.UPGRADE_VALIDATION_REQUIRED,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.UPGRADE_VALIDATION_REQUIRED]: [
    UPGRADE_STATES.UPGRADE_COMPLETED,
    UPGRADE_STATES.RECOVERY_REQUIRED,
    UPGRADE_STATES.FAILED_CLOSED,
  ],
  [UPGRADE_STATES.UPGRADE_COMPLETED]: [UPGRADE_STATES.EXISTING_INSTALL_READY],
  [UPGRADE_STATES.RECOVERY_REQUIRED]: [],
  [UPGRADE_STATES.FAILED_CLOSED]: [],
});

function assertKnownState(state) {
  if (!Object.values(UPGRADE_STATES).includes(state)) {
    const error = new Error(`Unknown upgrade state: ${state}`);
    error.code = 'UPGRADE_STATE_UNKNOWN';
    throw error;
  }
}

function assertTransition(fromState, toState) {
  assertKnownState(fromState);
  assertKnownState(toState);
  const allowed = ALLOWED_TRANSITIONS[fromState] || [];
  if (!allowed.includes(toState)) {
    const error = new Error(`Invalid upgrade transition from ${fromState} to ${toState}.`);
    error.code = 'UPGRADE_STATE_TRANSITION_INVALID';
    error.fromState = fromState;
    error.toState = toState;
    throw error;
  }
}

function isTerminalState(state) {
  return TERMINAL_STATES.has(state);
}

module.exports = {
  ALLOWED_TRANSITIONS,
  TERMINAL_STATES,
  UPGRADE_STATES,
  assertKnownState,
  assertTransition,
  isTerminalState,
};
